### ISSUE TITLE
Allow the CLI to handle -o paths without a trailing slash

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/celluster#2]
While
```
python3 /app/celluster.py -i /data/unmicst-exemplar-001.csv -o /data/
```
works, remove the trailing slash from the `-o` argument
```
python3 /app/celluster.py -i /data/unmicst-exemplar-001.csv -o /data
```
leads to an undefined variable `output`:
```
Traceback (most recent call last):
  File "/app/celluster.py", line 141, in <module>
    clean(args.input)
  File "/app/celluster.py", line 93, in clean
    data.to_csv(f'{output}/{CLEAN_DATA_FILE}', index=False)
NameError: name 'output' is not defined
```

**Comment by MattHodgman** [comment]
Resolved this issue.
